### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by howardjohn** [golangci/govet#1]
Running `govet` uses 18gb of memory when running on https://github.com/istio/istio which makes it not feasible to run in CI/on local environments. Is there any way to reduce memory usage?

**Comment by distorhead** [comment]
Try to update golangci-lint >= 1.52.1.

**Comment by howardjohn** [comment]
We have upgraded since then and I don't think we still have this issue. Not sure what our current memory usage is but its not that bad anymore. Thanks!
